# Generated by Django 2.1 on 2018-09-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180911_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('book_all', 'set_book_all'),)},
        ),
    ]
